[package]
name = "custom-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
data-encoding = "2.9.0"
num-bigint = "0.4.6"
ring = "0.17.14"
rust-crypto = "0.2.36"
serde= { version = "^1", features = ["derive"] }
sha2 = "0.10.8"
sled = "0.34.7"
